openapi: 3.0.0
info:
  title: Todo Api Specification
  version: 1.0.0
  description: API сервис для работы с задачами на платформе Netology
  contact:
    name: Anton Golomazov
    url: 'https://vk.com/agolomazov'
    email: cesear@bk.ru
  termsOfService: 'https://netology.ru/docs/api/todo'
servers:
  - url: 'http://localhost:3010'
x-json-schema-faker:
  locale: ru
  min-items: 2
  max-items: 10
  resolve-json-path: true
paths:
  /todos:
    get:
      summary: Получение списка задач
      tags:
        - Задачи
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
      operationId: getTodos
      description: Получение списка задач в системе
    post:
      summary: Создание новой задачи
      tags:
        - Задачи
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
      operationId: createTodo
      description: Создание новой сущности Задача
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
  '/todos/{todoId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: todoId
        in: path
        required: true
        description: ID задачи
    get:
      summary: Получение задачи по ID
      tags:
        - Задачи
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Not Found
      operationId: getTodoByID
      description: Получение задачи по ID
    put:
      summary: Замена задачи
      tags:
        - Задачи
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Bad Request
      operationId: updateTodoByID
      description: Обновление данных о задаче
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        description: Сущность задачи для обновления
    delete:
      summary: Удаление задачи
      tags:
        - Задачи
      responses:
        '204':
          description: No Content
      operationId: removeTodoByID
      description: Удаление задачи по ID
components:
  schemas:
    Todo:
      title: Задача
      type: object
      x-tags:
        - Заметка
      description: Сущность задачи на платформе
      properties:
        todoID:
          type: string
          format: uuid
          description: ID задачи
        title:
          type: string
          minLength: 2
          description: Заголовок задачи
          x-faker: lorem.paragraphs
        description:
          type: string
          description: Описание задачи
          x-faker: commerce.productDescription
          minLength: 5
        completed:
          type: boolean
          default: false
          description: Задача завершена
      required:
        - title
        - description
tags:
  - name: Задачи
    description: Задачи на платформе
    externalDocs:
      url: 'https://netology.ru/docs/todo'
